
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$fill\
$cmd_duration\
$status\
$line_break\
$character"""

[git_status]
ahead =	'⇡${count} '
behind =	'⇣${count} '
diverged =	'⇕${count} '
untracked =	'?${count} '
stashed =	'$${count} '
modified =	'!${count} '
staged =	'+${count} '
renamed =	'»${count} '
deleted =	'✘${count} '
format = '([$all_status$ahead_behind]($style) )'
style = 'bold green'

[cmd_duration]
min_time = 0

[status]
disabled=false
symbol=''
format=	'returned [$symbol$status]($style) '

[directory]
read_only = ' 🔒'
