
export STARSHIP_CONFIG=~/projects/rice/zsh/starship.toml
eval "$(starship init zsh)"

# Plugins and Themes
# Plugin Manager : Antigen

source /home/kevqn/projects/rice/zsh/antigen.zsh

antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle jeffreytse/zsh-vi-mode
antigen bundle Tarrasch/zsh-autoenv
antigen bundle "MichaelAquilina/zsh-autoswitch-virtualenv"
antigen apply

# Aliases
source "/home/kevqn/projects/rice/zsh/aliases.zsh"
source "/home/kevqn/projects/rice/zsh/ssh.zsh"

eval "$(zoxide init zsh)"

# Environment Variables
export BROWSER=vivaldi

# # To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
# [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Path
export PATH="/usr/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$PATH:$HOME/.local/bin/scripts-bin"
export GEM_HOME="/home/kevqn/.local/share/gem/ruby/3.0.0"
export PATH="$PATH:$GEM_HOME/bin"
export EDITOR="/usr/bin/nvim"
export VISUAL="/usr/bin/nvim"
export PATH="$PATH:/home/kevqn/.cargo/bin"

# fixes
export _JAVA_AWT_WM_NONREPARENTING=1    # this fixes misbehaving java apps

# ripgrep conf
export RIPGREP_CONFIG_PATH="$HOME/.config/ripgrep/ripgrep.conf"

# zsh autoenv options
export AUTOENV_FILE_ENTER=.enter.zsh
export AUTOENV_FILE_LEAVE=.leave.zsh
export AUTOENV_HANDLE_LEAVE=1

eval $(thefuck --alias)
