# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi


# Plugins and Themes
# Plugin Manager : Antigen

source /home/kevqn/projects/rice/zsh/antigen.zsh

antigen bundle zsh-users/zsh-autosuggestions
antigen theme romkatv/powerlevel10k
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle jeffreytse/zsh-vi-mode
antigen apply

# Aliases
source "/home/kevqn/projects/rice/zsh/aliases.zsh"

eval "$(zoxide init zsh)"

# Environment Variables
export BROWSER=vivaldi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Path
export PATH="/usr/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$PATH:$HOME/.local/bin/scripts-bin"
export GEM_HOME="/home/kevqn/.local/share/gem/ruby/3.0.0"
export PATH="$PATH:$GEM_HOME/bin"
export EDITOR="/usr/bin/nvim"
export VISUAL="/usr/bin/nvim"
export PATH="$PATH:/home/kevqn/.cargo/bin"

# fixes
export _JAVA_AWT_WM_NONREPARENTING=1    # this fixes misbehaving java apps

export RIPGREP_CONFIG_PATH="$HOME/.config/ripgrep/ripgrep.conf"
